name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for taking the time to create your first issue for our bot the devs will see this shortly'
        pr-message: 'Thank you for making your first pr on this repo the devs will review your pr soon'
